name: 'Cocos Creator Build'
description: 'A github action for cocos creator build'
author: 'miggene'
branding:
  icon: activity
  color: blue
inputs:
  cocos_download_url:
    required: false
    description: 'cocos creator download urls'
    default: 'https://creator-api.cocos.com/api/cocoshub/editor_version_list?lang=zh'

  cocos_version:
    required: false
    description: 'cocos creator version'
    default: '3.8.4'

  project_path:
    required: false
    description: 'project path for build'
    default: './'

  config_path :
    required: true
    description: 'config path for build'
    default: './web-desktop.json'

  upload_artifact :
    required: false
    description: 'whether upload artifact'
    default: true

runs:
  using: 'node12'
  main: 'dist/index.js'
